# Generated by Django 4.1.4 on 2022-12-22 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('developer_src', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='developer_logo')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField(default=1)),
                ('squares', models.IntegerField()),
                ('buy_price', models.IntegerField(default=0, help_text='$')),
                ('rent_price', models.IntegerField(default=0, help_text='$')),
                ('main_photo', models.ImageField(upload_to='estate_photos')),
                ('build_at', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.buildcompany')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstatePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='estate_photos')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.realestate')),
            ],
        ),
    ]
