# Generated by Django 4.1.4 on 2022-12-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_estatecomment_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatecomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
